quarkus:
  datasource:
    db-kind: postgresql
#    username: postgres
#    password: sdawra2183alkjfs
#    jdbc:
#      url: jdbc:postgresql://localhost:5432/postgres
  smallrye-openapi:
    enabled: true
    path: /openapi
    info-title: My API
    info-version: 1.0.1
    info-description: API documentation for my application
  swagger-ui:
    theme: original

test: test